### ISSUE TITLE
deep3Dpredict.py does not recognize .save file

### ISSUE THREAD

**Issue by reckbo** [GUR9000/Deep_MRI_brain_extraction#2]
There is a bug in `deep3Dpredict.py`:

    python Deep_MRI_brain_extraction/deep3Dpredict.py -n Deep_MRI_brain_extraction/OASIS_ISBR_LPBA40__trained_CNN.save -i  $target -gridsize 16
    ValueError: The provided save file/directory does not contain any saved model (file ending in .save)

I tracked the error to the line `candidates = findall(path_or_file)` which returns

```
['D', 'e', 'e', 'p', '_', 'M', 'R', 'I', '_', 'b', 'r', 'a', 'i', 'n', '_', 'e', 'x', 't', 'r', 'a', 'c', 't', 'i', 'o', 'n', '/.autofsck', 'O', 'A', 'S', 'I', 'S', '_', 'I', 'S', 'B', 'R', '_', 'L', 'P', 'B', 'A', '4', '0', '_', '_', 't', 'r', 'a', 'i', 'n', 'e', 'd', '_', 'C', 'N', 'N', ...
```

**Comment by GUR9000** [comment]
Thank you - there were indeed three misplaced characters in the code. It should be fixed now.
