### ISSUE TITLE
Markdown Correction examples in Readme.md

### ISSUE THREAD

**Issue by 0rC0** [GUR9000/Deep_MRI_brain_extraction#4]
There is some alignment/newline problem in section IV. Examples. 

Correction  as attachment. (I had to rename it in Readme.md.txt because the md extension was not accepted.

[Readme.md.txt](https://github.com/GUR9000/Deep_MRI_brain_extraction/files/1752052/Readme.md.txt)

**Comment by GUR9000** [comment]
Thank you, I merged your suggestion with some other changes in the latest commit.
