### ISSUE TITLE
Some question about code

### ISSUE THREAD

**Issue by Simon1zxb** [GUR9000/Deep_MRI_brain_extraction#6]
In Segmentation_predictor line 132
pred[c, x::CNET_stride[0], y::CNET_stride[1], z::CNET_stride[2]] = rr[0,:,c,:,:].reshape((pred_size[0], pred_size[1], pred_size[2]))

I really want to know why the pred's value is determined by this. I mean it jumps.
And at the top of this line I notice that you only shift the data one vixel but you can get twice output. I think it is overlap. Maybe I misunderstand your paper? I am really confused.

**Comment by GUR9000** [comment]
Please specify "I mean it jumps."

I'm also not quite sure what you mean by "only shift the data one vixel but you can get twice output".

Can you also provide an example or theoretical proof that the code is wrong, given that it works as it is? The shifts are there to account for pooling layers, but that should be clear from the rest of the code.

**Comment by Simon1zxb** [comment]
Maybe I also misunderstand the idea in your paper.
Take the inputSize = 65 as an example. The outputSize=7. It doesn't mean to predict the cube(7^3) in the core of the big cube(65^3)? So I don't know how can you get the outputSize = 14 just using only one big cube(65^3).
And also when padding the input data, why the offsetr = offsetl + inputSize. I mean I don't know why the right is padded more than left instead of be symmetric.
Really thanks for your reply.

**Comment by GUR9000** [comment]
All of this is done for efficiency. The same network could also predict only the central voxel, but then it would take several days to segment a data set instead of minutes.
